
package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;

import com.pedropathing.follower.Follower;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.util.ElapsedTime;

import org.firstinspires.ftc.teamcode.pedro.Constants;

@TeleOp(name="drive", group="Linear OpMode")
public class drive extends LinearOpMode {

    private ElapsedTime runtime = new ElapsedTime();

    private Follower follower;

    @Override
    public void runOpMode() {

        telemetry.addData("Status", "Initialized");
        telemetry.update();

        waitForStart();
        runtime.reset();

        follower = Constants.create(hardwareMap);

        while (opModeIsActive()) {





            telemetry.addData("Left Stick", gamepad1.left_stick_x);

            follower.manual( //this does not work and I can't figure out why
                    -gamepad1.left_stick_y,
                    gamepad1.left_stick_x,
                    gamepad1.right_stick_x
            );
            follower.update();
        }
    }
}